name: MARN-3060
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - numpy
  - matplotlib
  - dask
  - pandas
  - xarray
  - xgcm
  - netcdf4
  - cmocean
  - gsw
  - xhistogram
  - jupyterlab
  - ipykernel
  - wget
  - curl
  - pip
  - cartopy 
  - ipympl
